
server:
  port: 8761

eureka:
  instance:
    hostname: registry-server
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

spring:
  application:
    name: SERVICE-REGISTRY

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
