
server:
  port: 8888

spring:
  application:
    name: ROUTING-GATEWAY
  cloud:
    discovery:
      enabled: true
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        register: true
    eureka:
      client:
        service-url:
          defaultZone: http://registry-server:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

eureka:
  instance:
    hostname: routing-gateway
